# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "jj-dojo",
    version = "0.0.1",
)

bazel_dep(name = "aspect_rules_js", version = "3.1.1")
bazel_dep(name = "aspect_rules_ts", version = "3.8.9")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_nodejs", version = "6.7.4")
bazel_dep(name = "rules_shell", version = "0.6.1")




npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)

npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
    npmrc = "//:.npmrc",
)
use_repo(npm, "npm")

# Enable pnpm toolchain for lockfile verification
pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm", dev_dependency = True)
pnpm.pnpm(pnpm_version = "9.1.0") # Pin pnpm version. Must align with version in .github/workflows/lint.yaml.
use_repo(pnpm, "pnpm")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext", dev_dependency = True)
rules_ts_ext.deps()
use_repo(rules_ts_ext, "npm_typescript")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "addlicense_linux_amd64",
    build_file_content = 'exports_files(["addlicense"])',
    integrity = "sha256-aSQpZ3EjSxumyWnhCbRFnP914Vsllna2Hfh0qSc0skI=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_Linux_x86_64.tar.gz"],
)

http_archive(
    name = "addlicense_linux_arm64",
    build_file_content = 'exports_files(["addlicense"])',
    integrity = "sha256-sU3ehnptvNQf30UJaD4Xf0UAvwE0aT04xWcB4Xnz81M=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_Linux_arm64.tar.gz"],
)

http_archive(
    name = "addlicense_darwin_amd64",
    build_file_content = 'exports_files(["addlicense"])',
    integrity = "sha256-M1tHooqrxuOUlCIv1xwivUDRTW9tCgirnqfG8xVViIM=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_macOS_x86_64.tar.gz"],
)

http_archive(
    name = "addlicense_darwin_arm64",
    build_file_content = 'exports_files(["addlicense"])',
    integrity = "sha256-BZcwXGGfc0l0joMOODItvn0Tz4bPQVsom8D1zsu0v2M=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_macOS_arm64.tar.gz"],
)

http_archive(
    name = "addlicense_windows_amd64",
    build_file_content = 'exports_files(["addlicense.exe"])',
    integrity = "sha256-/k9KVOqkp1D/p9Gw2kcdB3rCTwDaTX8fe3lQlp0lS5k=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_Windows_x86_64.zip"],
)

http_archive(
    name = "addlicense_windows_arm64",
    build_file_content = 'exports_files(["addlicense.exe"])',
    integrity = "sha256-MquP906btdVHrLnw7tOW3uHjqG66xqR7t8Ne0mlAsho=",
    urls = ["https://github.com/google/addlicense/releases/download/v1.2.0/addlicense_v1.2.0_Windows_arm64.zip"],
)