#!/usr/bin/env python3
#
# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import os
import re
import subprocess
import sys


def main():
  # Resolve paths relative to the script's location
  script_dir = os.path.dirname(os.path.abspath(__file__))
  repo_root = os.path.dirname(script_dir)

  # Check if `npm run lint` is clean.
  try:
    subprocess.run(['npm', 'run', 'lint'], cwd=repo_root, check=True)
  except subprocess.CalledProcessError as e:
    print(
        'Fix the `npm run lint` errors first before executing this'
        f' script`: {e}',
        file=sys.stderr,
    )
    sys.exit(1)

  # Find the location of the currently installed vscode package
  vscode_types_dir = os.path.join(repo_root, 'node_modules', '@types', 'vscode')
  if not os.path.exists(vscode_types_dir):
    print(
        f'Error: Cannot find vscode types directory at {vscode_types_dir}',
        file=sys.stderr,
    )
    print('Please run npm install or pnpm install first.', file=sys.stderr)
    sys.exit(1)

  real_vscode_dir = os.path.realpath(vscode_types_dir)
  print(f'Found vscode types package at: {real_vscode_dir}')

  # Read the index.d.ts file
  index_dts_path = os.path.join(real_vscode_dir, 'index.d.ts')
  if not os.path.exists(index_dts_path):
    print(f'Error: Cannot find index.d.ts at {index_dts_path}', file=sys.stderr)
    sys.exit(1)

  with open(index_dts_path, 'r', encoding='utf-8') as f:
    content = f.read()

  # Use regular expression to get all enums in it including its documentation
  # Supports matching balanced braces for comments like {@link ...} inside the enum body
  pattern = re.compile(
      r'(?:(/\*\*(?:(?!\*/).)*\*/\s*))?(export\s+enum\s+\w+\s*\{(?:[^{}]|\{[^{}]*\})*\})',
      re.DOTALL,
  )

  matches = pattern.findall(content)
  if not matches:
    print('Error: No enums found in index.d.ts', file=sys.stderr)
    sys.exit(1)

  print(f'Extracted {len(matches)} enums.')

  # Extract the original LICENSE header from the top of the file
  header_match = re.match(r'^\s*(/\*.*?\*/)', content, re.DOTALL)
  original_header = header_match.group(1) if header_match else ''

  # Format the extracted enums
  enums_content = []
  for doc, enum_def in matches:
    block = ''
    if doc:
      block += doc
    block += enum_def
    enums_content.append(block)

  # Prepare output content
  output_parts = []
  if original_header:
    output_parts.append(original_header)
  output_parts.append(
      '// This file is auto-generated by scripts/populate_vscode_enum.py. Do'
      ' not edit directly.'
  )
  output_parts.append('\n\n'.join(enums_content))

  output_content = '\n\n'.join(output_parts) + '\n'

  # Destination directory: third_party/vscode
  dest_dir = os.path.join(repo_root, 'third_party', 'vscode')
  os.makedirs(dest_dir, exist_ok=True)

  # Paste them in third_party/vscode/vscode_enums.ts
  output_path = os.path.join(dest_dir, 'vscode_enums.ts')
  with open(output_path, 'w', encoding='utf-8') as f:
    f.write(output_content)
  print(f'Successfully wrote enums to {output_path}')

  # Run `npm run fix` to format the generated file.
  print('Running `npm run fix` to format the generated file...')
  try:
    subprocess.run(['npm', 'run', 'fix'], cwd=repo_root, check=True)
    print('Successfully ran `npm run fix`.')
  except subprocess.CalledProcessError as e:
    print(f'Error running `npm run fix`: {e}', file=sys.stderr)
    sys.exit(1)

  # Copy the LICENSE file in the directory to third_party/vscode/LICENSE
  src_license = os.path.join(real_vscode_dir, 'LICENSE')
  dest_license = os.path.join(dest_dir, 'LICENSE')
  subprocess.run(['cp', src_license, dest_license], check=True)
  print(f'Successfully copied LICENSE to {dest_license}')


if __name__ == '__main__':
  main()
