name: 'test-postsubmit'

on:
  push:
    branches:
      - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  test:
    uses: './.github/workflows/_test_run.yaml'
